/**
 * Exports content-level data from THIS database into a re-runnable SQL file,
 * so a deployed instance (Render) can be brought in line with local work.
 *
 *   node other-tools/export-sync.js
 *   node other-tools/export-sync.js --reference-db neurolex_pristine
 *   node other-tools/export-sync.js --out ../sql/sync-content.sql
 *
 * What it exports:
 *   tags            - the taxonomy, including anything renamed or added in the app
 *   notebook_tags   - which notebooks carry which tags
 *   vocab_tags      - which words carry which function tags
 *   notebooks       - title / slug / description for built-in notebooks
 *   vocabulary      - the meaning fields (this is where hand-edited DeepL
 *                     translations live, which no importer can reproduce)
 *
 * What it does NOT export: users, passwords, review progress, question attempts.
 * Those are per-environment and must not be copied between deployments.
 *
 * Everything is keyed on NATURAL keys - vocabulary.word, tags.slug,
 * notebooks.slug - never on numeric ids, because the ids on Render are assigned
 * by its own seed run and will not match this machine's.
 *
 * --reference-db points at a freshly seeded database on the same server. When
 * given, only vocabulary rows that DIFFER from that pristine seed are exported,
 * which isolates genuine hand edits instead of restating what the seed already
 * produces. Without it, every row is exported (larger file, same end state).
 */
const fs = require('fs');
const path = require('path');
const { createPool, poolConfig, describeTarget } = require('../db');

const argv = process.argv.slice(2);
const argOf = (name) => {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : null;
};

const referenceDb = argOf('--reference-db');
const outPath = path.resolve(__dirname, argOf('--out') || '../sql/sync-content.sql');

const pool = createPool();

/** Quotes a value as a SQL literal. */
function lit(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  return "'" + String(v).replace(/'/g, "''") + "'";
}

const MEANING_FIELDS = ['meaning', 'english_meaning', 'vietnamese_meaning', 'synonyms', 'phonetic', 'example'];

async function loadReferenceVocabulary() {
  if (!referenceDb) return null;
  const cfg = poolConfig();
  // Same server, different database.
  const refPool = createPool(
    cfg.connectionString
      ? { connectionString: cfg.connectionString.replace(/\/[^/?]+(\?|$)/, `/${referenceDb}$1`) }
      : { database: referenceDb }
  );
  try {
    const r = await refPool.query(
      `SELECT LOWER(word) AS w, ${MEANING_FIELDS.join(', ')} FROM vocabulary`
    );
    return new Map(r.rows.map((row) => [row.w, row]));
  } finally {
    await refPool.end();
  }
}

function differs(row, ref) {
  if (!ref) return true;
  return MEANING_FIELDS.some((f) => (row[f] || '') !== (ref[f] || ''));
}

function chunkedInsert(lines, header, rows, rowToValues, conflict, chunkSize = 200) {
  for (let i = 0; i < rows.length; i += chunkSize) {
    const slice = rows.slice(i, i + chunkSize);
    lines.push(header);
    lines.push(slice.map(rowToValues).join(',\n'));
    lines.push(conflict);
    lines.push('');
  }
}

async function main() {
  const reference = await loadReferenceVocabulary();
  const client = await pool.connect();
  const L = [];
  const stats = {};

  try {
    L.push('-- sync-content.sql');
    L.push('-- Generated by other-tools/export-sync.js on ' + new Date().toISOString());
    L.push('-- Source: ' + describeTarget());
    L.push('--');
    L.push('-- Brings a deployed database in line with local content: tags, tag');
    L.push('-- assignments, notebook naming and hand-edited word meanings.');
    L.push('--');
    L.push('-- Safe to run repeatedly. Keyed on natural keys (word, slug), never on');
    L.push('-- numeric ids, so it does not care that ids differ between machines.');
    L.push('-- Touches no users, no review progress and no question attempts.');
    L.push('--');
    L.push('--   psql "$DATABASE_URL" -f server/sql/sync-content.sql');
    L.push('');
    L.push('-- This file is UTF-8. On Windows psql defaults client_encoding to the');
    L.push('-- console codepage (WIN1252), which makes it read the Vietnamese meanings');
    L.push('-- and IPA symbols as mojibake and abort with');
    L.push("--   ERROR: character with byte sequence 0x8f in encoding \"WIN1252\"");
    L.push('-- Setting it here means the file works whatever codepage the caller uses.');
    L.push("SET client_encoding = 'UTF8';");
    L.push('');
    L.push('BEGIN;');
    L.push('');

    /* ---------------- tags ---------------- */
    const tags = (await client.query(
      'SELECT slug, label, kind, scope, description FROM tags ORDER BY kind, slug'
    )).rows;
    stats.tags = tags.length;
    L.push('-- ' + tags.length + ' tags -------------------------------------------------');
    chunkedInsert(L,
      'INSERT INTO tags (slug, label, kind, scope, description) VALUES',
      tags,
      (t) => `  (${lit(t.slug)}, ${lit(t.label)}, ${lit(t.kind)}, ${lit(t.scope)}, ${lit(t.description)})`,
      `ON CONFLICT (slug) DO UPDATE SET
  label = EXCLUDED.label, kind = EXCLUDED.kind,
  scope = EXCLUDED.scope, description = EXCLUDED.description;`
    );

    /* ---------------- notebook naming ---------------- */
    const notebooks = (await client.query(
      `SELECT slug, title, topic, difficulty, description
       FROM notebooks WHERE owner_user_id IS NULL AND slug IS NOT NULL ORDER BY slug`
    )).rows;
    stats.notebooks = notebooks.length;
    L.push('-- ' + notebooks.length + ' built-in notebooks: canonical naming ------------------');
    L.push('-- Matched on slug. A notebook missing on the target is left alone: the');
    L.push('-- seed there creates it, this only corrects naming and description.');
    for (const nb of notebooks) {
      L.push(`UPDATE notebooks SET title = ${lit(nb.title)}, topic = ${lit(nb.topic)}, ` +
             `difficulty = ${lit(nb.difficulty)}, description = ${lit(nb.description)} ` +
             `WHERE slug = ${lit(nb.slug)} AND owner_user_id IS NULL;`);
    }
    L.push('');

    /* ---------------- vocabulary meanings ---------------- */
    const vocab = (await client.query(
      `SELECT word, ${MEANING_FIELDS.join(', ')} FROM vocabulary ORDER BY word`
    )).rows;
    const changed = vocab.filter((v) => differs(v, reference ? reference.get(v.word.toLowerCase()) : null));
    stats.vocabTotal = vocab.length;
    stats.vocabExported = changed.length;

    L.push('-- ' + changed.length + ' vocabulary rows ' +
           (reference ? '(only those differing from a pristine seed) ' : '(all) ') + '-------');
    L.push('-- These carry hand-edited meanings that no importer can regenerate.');
    L.push('-- A word missing on the target is inserted; an existing one is updated.');
    chunkedInsert(L,
      'INSERT INTO vocabulary (word, meaning, english_meaning, vietnamese_meaning, synonyms, phonetic, example) VALUES',
      changed,
      (v) => `  (${lit(v.word)}, ${lit(v.meaning)}, ${lit(v.english_meaning)}, ` +
             `${lit(v.vietnamese_meaning)}, ${lit(v.synonyms)}, ${lit(v.phonetic)}, ${lit(v.example)})`,
      `ON CONFLICT (word) DO UPDATE SET
  meaning = EXCLUDED.meaning, english_meaning = EXCLUDED.english_meaning,
  vietnamese_meaning = EXCLUDED.vietnamese_meaning, synonyms = EXCLUDED.synonyms,
  phonetic = EXCLUDED.phonetic, example = EXCLUDED.example;`
    );

    /* ---------------- notebook_tags ---------------- */
    const nbTags = (await client.query(
      `SELECT n.slug AS notebook_slug, t.slug AS tag_slug
       FROM notebook_tags nt
       JOIN notebooks n ON n.id = nt.notebook_id
       JOIN tags t ON t.id = nt.tag_id
       WHERE n.owner_user_id IS NULL AND n.slug IS NOT NULL
       ORDER BY n.slug, t.slug`
    )).rows;
    stats.notebookTags = nbTags.length;
    L.push('-- ' + nbTags.length + ' notebook tag assignments ---------------------------');
    chunkedInsert(L,
      `INSERT INTO notebook_tags (notebook_id, tag_id)
SELECT n.id, t.id FROM (VALUES`,
      nbTags,
      (r) => `  (${lit(r.notebook_slug)}, ${lit(r.tag_slug)})`,
      `) AS v(nb_slug, tag_slug)
JOIN notebooks n ON n.slug = v.nb_slug AND n.owner_user_id IS NULL
JOIN tags t ON t.slug = v.tag_slug
ON CONFLICT DO NOTHING;`
    );

    /* ---------------- vocab_tags ---------------- */
    const vTags = (await client.query(
      `SELECT v.word, t.slug AS tag_slug
       FROM vocab_tags vt
       JOIN vocabulary v ON v.id = vt.vocab_id
       JOIN tags t ON t.id = vt.tag_id
       ORDER BY v.word, t.slug`
    )).rows;
    stats.vocabTags = vTags.length;
    L.push('-- ' + vTags.length + ' word tag assignments -------------------------------');
    chunkedInsert(L,
      `INSERT INTO vocab_tags (vocab_id, tag_id)
SELECT v.id, t.id FROM (VALUES`,
      vTags,
      (r) => `  (${lit(r.word)}, ${lit(r.tag_slug)})`,
      `) AS x(word, tag_slug)
JOIN vocabulary v ON v.word = x.word
JOIN tags t ON t.slug = x.tag_slug
ON CONFLICT DO NOTHING;`
    );

    /* ---------------- cleanup of a known source defect ---------------- */
    // assets/va-c1c2-500-2023-2026.csv used to contain 29 words split by a PDF
    // line wrap ("circumspecti on"), which older seeds inserted verbatim
    // alongside the correct spelling. The CSV is fixed now, but a database
    // seeded before that fix still carries the broken rows.
    //
    // Deliberately narrow: only a row whose word contains a space, whose
    // de-spaced form ALSO exists as its own word, and which no user has any
    // review progress on. Real multi-word entries ("give rise to") never match,
    // because "giveriseto" is not a word.
    L.push('-- Remove split-word rows left by the old CSV defect ----------------');
    L.push(`DELETE FROM vocabulary v
WHERE v.word LIKE '% %'
  AND EXISTS (SELECT 1 FROM vocabulary w WHERE w.word = REPLACE(v.word, ' ', '') AND w.id <> v.id)
  AND NOT EXISTS (SELECT 1 FROM user_vocab_progress p WHERE p.vocab_id = v.id);`);
    L.push('');

    L.push('COMMIT;');
    L.push('');

    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, L.join('\n'), 'utf8');

    const kb = Math.round(fs.statSync(outPath).size / 1024);
    console.log(`✅ Wrote ${outPath} (${kb} KB)`);
    console.log(`   tags:            ${stats.tags}`);
    console.log(`   notebooks:       ${stats.notebooks} (naming only)`);
    console.log(`   notebook_tags:   ${stats.notebookTags}`);
    console.log(`   vocab_tags:      ${stats.vocabTags}`);
    console.log(`   vocabulary:      ${stats.vocabExported} of ${stats.vocabTotal}` +
                (reference ? ` (differ from "${referenceDb}")` : ' (all rows)'));
    if (!reference) {
      console.log('\n   Tip: pass --reference-db <freshly-seeded-db> to export only the');
      console.log('   rows you actually hand-edited, instead of every row.');
    }
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error('❌', err.message);
  process.exit(1);
});
